version: '3.8'

services:

  config-server:
    build: ./Config-Server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - parcial-network
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/nostcoper/Desarrollo-Basados-en-Servicios.git
      - SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS=Enigma Api Webflux/Config-repo
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://config-server:8888/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 5

  orquestador:
    build: ./Orquestador
    container_name: orquestador
    ports:
      - "8080:8080"
    networks:
      - parcial-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://orquestador:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy

  step-one-api:
    build: ./Step-One-Api
    container_name: step-one-api
    ports:
      - "8081:8081"
    networks:
      - parcial-network
    depends_on:
      config-server:
        condition: service_healthy


  step-two-api:
    build: ./Step-Two-Api
    container_name: step-two-api
    ports:
      - "8082:8082"
    networks:
      - parcial-network
    depends_on:
      config-server:
        condition: service_healthy


  step-three-api:
    build: ./Step-Three-Api
    container_name: step-three-api
    ports:
      - "8083:8083"
    networks:
      - parcial-network
    depends_on:
      config-server:
        condition: service_healthy


  webhook:
    build: ./Webhook
    container_name: webhook
    ports:
      - "8091:8091"
    networks:
      - parcial-network
    depends_on:
      orquestador:
        condition: service_healthy


  batch:
    build: ./Batch
    container_name: batch
    ports:
      - "8090:8090"
    networks:
      - parcial-network
    depends_on:
      orquestador:
        condition: service_healthy


networks:
  parcial-network:
    driver: bridge